# Generated by Django 4.1.3 on 2022-12-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_alter_blog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha_publicacion',
            field=models.DateField(),
        ),
    ]
