# Generated by Django 4.1.3 on 2022-12-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_blog_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
