# Generated by Django 4.1.3 on 2022-12-24 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('ide', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('leido', models.BooleanField(default=False)),
                ('userDestinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userDestinatario', to=settings.AUTH_USER_MODEL)),
                ('userRemitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRemitente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
